spring:
  application:
    name: rider

  output:
    ansi:
      enabled: always
  profiles:
    active: local

security:
  permit-all:
    urls: /v0/login, /v0/signup, /error

rider:
  roster:
    key: on_duty